<a href="https://colab.research.google.com/github/akasaa101/MyColabNotebooks/blob/master/mnist_kendi_modelim1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from keras.datasets import mnist
#mnist data setini indirip eğitim datası(train) ve test datası olarak ayırıyoruz
(X_train, y_train),(X_test,y_test)=mnist.load_data()


In [0]:
#dataset de ki ilk resmi yazdırıyoruz
import matplotlib.pyplot as plt

plt.imshow(X_train[0])

In [0]:
#fotoğrafın shape ini kontrol ediyoruz
X_train[0].shape

(28, 28)

In [0]:
#modeli fitleştirmek için datayı reshape yapmamız gerekiyor
X_train=X_train.reshape(60000,28,28,1)
X_test=X_test.reshape(10000,28,28,1)

In [0]:
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [0]:
#Modeli oluşturuyoruz.
from keras.models import Sequential
from keras.layers import Dense,Conv2D, Flatten

model=Sequential()


model.add(Conv2D(64,kernel_size=3,activation='relu',input_shape=(28,28,1)))
model.add(Conv2D(32,kernel_size=3,activation='relu'))
model.add(Flatten())
model.add(Dense(10,activation='softmax'))

#Model türümüzü sequental yani sıralı olarak belirledik.
#Sequental model oluşturmanın en kolay yoludur
#Modelimizi katman katman oluşturmamıza olanak sağlar
#Modelimize katmanları eklemek için add() fonksiyonunu kullandık

#ilk iki katmanımız Conv2D katman. bu evşirimli katmanlar 2 boyutlu matrisimize input imagesi mizi alır (mı acaba?xD)
#ilk katmanda 64 node var ikinci katmanda 32 node var bu numaralar daha yüksek veya alçak olabilir. 64 ve 32 bizde çalışacaktır.
#Kernel(çekirdek) size 3 dedik. bu da evşirimli matriximmizin 3x3 boyutunda demek. 
#Activaston fonksiyonu Cnn için biz 2 sine relu kullandır. relunun iyi olduğu kanıtlanmıştır. ama araştır dany bunu.
#ilk katmanımız ayrıca boyut alıyor..
#ilk katmanımız aynı zamanda bir girdi şeklinde(inputsape). burada ki 1 greyscale(gri tonlaması) içindir.

#Conv2D katmanı ile Dense katmanımız vardır. Bu iki katmanın arasında yassılaştırma geçiş işlemlerini görür.

#Dense bizim çıkış katmanımızdır (output). Dense birçok nöral ağ durumunda standart kayman olarak kullanılabilr.
#bizim possible 10 outputumuz olduğu için 10 tane output node u belirttik
#aktivasyonumuzu softmax melirledik. Bu çıktıyı 1 e toplar ve çıktı olasılık olarak yorumlanabilir. Daha sonra model en yüksek olasılığa sahip olana bakarak tahminde bulunur.


In [0]:
#modeli model performansı ve modelin doğruluğunu kullanmak için compile ediyoruz?

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
#optimizer için adam ı kullandık. Bunu araştır
#leraning rate diye birşeye etki eder bu adam onu da bak
#loss da ki categorical_crossentropy classification için yaygın kullanımdır.. Düşük bir skor performansı arttırabilr.
#işlerim yorumlanmasını kolaylaştırmak için modeli eğittiğimizde doğrulama setinde i doğruluk puanını kullanacağız


In [0]:
#Veeeee oluşturduğumuz modeliii artıkkk eğitiyoruzzz

#epoch sayısı modelimiz ne kadar döngü yapacağını gösterir. ne kadar çok olursa model o kadar çok gelişebilir
#ancak bir noktadan sonra model gelişimini durduracaktır.


model.fit(X_train,y_train, validation_data=(X_test,y_test),epochs=3)

Instructions for updating:
Use tf.cast instead.
Train on 60000 samples, validate on 10000 samples
Epoch 1/3
60000/60000 [==============================] - 198s 3ms/step - loss: 14.3325 - acc: 0.1106 - val_loss: 14.4612 - val_acc: 0.1028
Epoch 2/3
60000/60000 [==============================] - 195s 3ms/step - loss: 14.4351 - acc: 0.1044 - val_loss: 14.4612 - val_acc: 0.1028
Epoch 3/3
60000/60000 [==============================] - 193s 3ms/step - loss: 14.4351 - acc: 0.1044 - val_loss: 14.4612 - val_acc: 0.1028


In [0]:
#şimdi modelimizi test ediyoruzzz.. olmadı ama olsun hiç olmazsa anladık xD
model.predict(X_test[:4])


array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]], dtype=float32)

In [0]:
y_test[:4]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)